### ISSUE TITLE
Using the pain scale image as a radio button doesn't save the data

### ISSUE THREAD

**Issue by uiowajs** [ctsit/imagemap#11]
If you click a face, save, and look at the form or data, the face won't be clicked anymore and the data won't be saved.  It still works as a text field.

**Comment by marlycormar** [comment]
Hi @uiowajs, thank you for using our module. Imagemap was implemented to support only text boxes, so it makes sense that it doesn't behave well for other field types.

**Comment by pbchase** [comment]
I am closing this as we have no plans to implement radio button support.
