### ISSUE TITLE
Rheumatoid man imagemap not functioning correctly

### ISSUE THREAD

**Issue by BlaineVlan** [ctsit/imagemap#23]
Hi there imagemap team,

I have been attempting to incorporate the new Rheumatoid man map into my project. I am running image map v 1.4.0, and the admins have enabled the external module on my project. 

When I attempt to run the module (as per the three methods below) the image of the rheumatoid man appears, but the joints cannot be selected, and do not highlight when clicked. 

I have tried three methods:

1. -  Using the “text box” function, inserting the action tag “@imagemap=rheumatoid_man”.
2. -  Using the “checkbox, multiple answers” function, inserting the correlating terminology 
       (ie: f01, Left Temporomandibular) as well as the action tag
3. -  Downloading the example CSV practice file

 All three of the above methods yield the same result: The image is present, however there are no clickable areas. I have tested the painmap module using the above methods, which works perfectly. 

Is there something that I am doing wrong my side, or is it a problem with the rheumatoid man in general?

Thanks in advance,

Blaine

**Comment by marlycormar** [comment]
Hi @BlaineVlan, thank you for reaching out. I have created an example instrument for you to try out. Can you check if you are able to click on the rheumatoid-man regions? Here is the instrument: 
[RheumatoidManExample.zip](https://github.com/ctsit/imagemap/files/3254071/RheumatoidManExample.zip)

Below are two screenshots: one screenshot is of the **Checkboxes (Multiple Answers)** field containing the imagemap and another of the rheumatoid-man with some regions highlighted:

<img width="817" alt="checkboxes_field" src="https://user-images.githubusercontent.com/8559654/58906811-14838900-870d-11e9-8281-a5df6b7fed34.png">,

<img width="780" alt="rheumatoid_man" src="https://user-images.githubusercontent.com/8559654/58906825-1c432d80-870d-11e9-9cd4-abc74b060be8.png">

**Comment by BlaineVlan** [comment]
Thanks for getting back to me so quickly @marlycormar .

I downloaded that instrument, there is still no change, I am unable to click on the areas. Recreated the same instrument identical to your screenshot, same result. It clearly works on your side, so is it perhaps something that needs to be enabled my side from an administrator?

Could any of the following be creating an issue:
-Running MacOS Mojave
-Accessing through chrome
-Running Redcap 8.4.3
-Imagemap v1.4.0

I can't think of any other differences, everything else appears identically, and works with the other imagemap files.

Thanks again,

Blaine

**Comment by marlycormar** [comment]
@BlaineVlan, I was able to reproduce your issue on REDCap 8.4.3. We are currently using REDCap 9.0.3. Let me try to make it work for older versions of REDCap. If I am unsuccessful, I will increase the minimum version required for the module to work.

**Comment by marlycormar** [comment]
Hi @BlaineVlan, I was able to reproduce your issue and it is now fixed. I have submitted the new imagemap version 1.4.1 to REDCap for review. I will let you know once is accepted so you can test it and let us know if your issue is fixed.

**Comment by marlycormar** [comment]
Hi @BlaineVlan, imagemap v1.4.1 has already been released. It contains a fix for the issue you were experiencing.

**Comment by pbchase** [comment]
addressed by PR #24
