### ISSUE TITLE
Add new Image map to the imagemap module

### ISSUE THREAD

**Issue by aallenkumc** [ctsit/imagemap#28]
[image-mbody-map-master.zip](https://github.com/ctsit/imagemap/files/3283123/image-mbody-map-master.zip)

These are the 3 files that are contained in the zip file
bodymap.png
config.json
mbody.html

**Comment by pbchase** [comment]
@marlycormar, do you want this one? If you're busy @ChemiKyle could use a little work. 

Either way, the zip file seems to have all the parts we need to make a make a PR to add the new map.

**Comment by marlycormar** [comment]
Sounds good. However, I think it's better if @ChemiKyle works on PR #19 (it is older) and seems to have all the needed components as well.

**Comment by marlycormar** [comment]
Hi @aallenkumc, can you provide a description of the image and a person to acknowledge for providing the image?

**Comment by aallenkumc** [comment]
Description is Michigan Body Map by the University of Michigan Division of Pain Research Anesthesiology There is a copyright on the bottom (2015 Regents of the University of Michigan) if that also needs to be listed. If you need anything else please let me know.

Angelica Allen

**Comment by marlycormar** [comment]
Thanks @aallenkumc. This image will be included in the next release of imagemap.
