### ISSUE TITLE
MBody Map changes to image size and output.

### ISSUE THREAD

**Issue by jrpence** [ctsit/imagemap#48]
<a href="https://github.com/aallenkumc"><img src="https://avatars1.githubusercontent.com/u/33663879?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aallenkumc](https://github.com/aallenkumc)**
_Thu Aug  8 19:24:46 2019_
_Originally opened as https://github.com/marlycormar/imagemap/issues/11_

----

Hello,

I developed the html and json for the MBody map for a user. When viewing the image in the REDCap system, the image is bigger then expected and they would like for it to be smaller. The output of the selections are listed in one field. They would prefer to have each selection as a checkbox and the values be 1 or 0. Can you let me  know what I would need to do to accomplish these changes?

Thanks,
Angelica Allen
University of Kansas Medical Center - Medical Informatics

**Comment by jrpence** [comment]
<a href="https://github.com/marlycormar"><img src="https://avatars3.githubusercontent.com/u/8559654?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marlycormar](https://github.com/marlycormar)**
_Thu Jul 16 00:37:52 2020_

----

Hi @ChemiKyle! Can you check if this issue is still of interest?

**Comment by jrpence** [comment]
<a href="https://github.com/ChemiKyle"><img src="https://avatars1.githubusercontent.com/u/20332546?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChemiKyle](https://github.com/ChemiKyle)**
_Thu Jul 16 13:08:26 2020_

----

@jrpence

**Comment by jrpence** [comment]
<a href="https://github.com/jrpence"><img src="https://avatars3.githubusercontent.com/u/1508198?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jrpence](https://github.com/jrpence)**
_Fri Jul 17 20:41:48 2020_

----

To make the Mbody image map smaller:
   Leave the mapping coordinates where they are (they will be scaled with the image).
   change the width and height in the config.json
     (scale 75% = 776 by 642, scale 50% = 576 by 428)

**Comment by pbchase** [comment]
Addresses by PR #50
