### ISSUE TITLE
Checkboxes cannot be used as input fields

### ISSUE THREAD

**Issue by pbchase** [ctsit/imagemap#55]
Checkboxes cannot be used as input fields. To reproduce this issue, load the example instrument, active the module, add a record and scroll down to the PAINMAP_FEMALE_OPTIONS example. The checkboxes on the left highlight the corresponding region when selected. 

Yet I'm not sure this matters in practice. The appearance of the checkboxes seems to be nothing more than a developer feature that would allow immediate feedback when testing image map regions. I don't see the use case for exposing these in production.

I doubt this is worth fixing, but it might be worth documenting

**Comment by 123andy** [comment]
I just did a minor tweak and got this working again - in next PR.

**Comment by mbentz-uf** [comment]
@pbchase With the changes the PR introduces checkboxes function as follows:
- When a checkbox is selected nothing happens to the image map
- When a region is selected the corresponding checkbox is toggled

Is that the expected behavior?

**Comment by 123andy** [comment]
@mbentz-uf  - not that isn't the intended behavior... it might not be fixed then.  Most people do not show the checkbox regions anyhow so it isn't that important.  Maybe we should leave this open.   The whole code could use a minor refactor but who has the time...  The major push for this release was to address an error affecting many users with more recent versions of redcap...

**Comment by mbentz-uf** [comment]
Thanks for clarifying @123andy

**Comment by ChemiKyle** [comment]
This issue is _partially_ fixed.

Selecting a region will select the checkbox, but electing a checkbox does **not** highlight the region _until page reload_. The issues with the imagemap library are much more important, so I will not address this in 1.9.0.

**Comment by pbchase** [comment]
> Selecting a region will select the checkbox, but electing a checkbox does **not** highlight the region _until page reload_. The issues with the imagemap library are much more important, so I will not address this in 1.9.0.

This is addressed by PR #65
