### ISSUE TITLE
Reduce size of description in config.json

### ISSUE THREAD

**Issue by 123andy** [ctsit/imagemap#9]
In comparison to other modules, the imagemap takes up too much precious real estate in the modules table... I'd recommend condensing it down to 2-3 lines...

The see documentation line is also a bit redundant is there is now and official documentation link auto-added...
<img width="715" alt="2018-03-21_1735" src="https://user-images.githubusercontent.com/7461553/37744785-4d980c78-2d2e-11e8-9a35-f19f07c3f13c.png">

**Comment by pbchase** [comment]
This was done sometime back.
